# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Everyapi < Formula
  desc "EveryAPI CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://everyapi.ai"
  version "3.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.5.0/everyapi_darwin_amd64.tar.gz"
      sha256 "ef48ffd4e8a0881be51bf9ac7086c043c18c20fe13d7743714cb76b5cff5f7a6"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.5.0/everyapi_darwin_arm64.tar.gz"
      sha256 "0a5db2db2bb7ee5eadd339b29cfaccbf4e30cfa96b4dae7aba734646f24baccb"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.5.0/everyapi_linux_amd64.tar.gz"
      sha256 "406f107474180150a3813cffb0e704ca73f9b035c09995a0b7a76db623a02f71"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.5.0/everyapi_linux_arm64.tar.gz"
      sha256 "71b097bd43225f473b8ce0eb9d25effb17fe279e97524a22d6f84986f7ffc9d2"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  test do
    assert_match "everyapi", shell_output("#{bin}/everyapi version")
    output = pipe_output("#{bin}/everyapi mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
