# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Everyapi < Formula
  desc "EveryAPI CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://everyapi.ai"
  version "0.14.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v0.14.4/everyapi_darwin_amd64.tar.gz"
      sha256 "4c549d94a76494c668b2c0b00f3b51669da0a9d37f3214b154e3a851ff00adbd"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v0.14.4/everyapi_darwin_arm64.tar.gz"
      sha256 "5db750915269b758bbcf8527438f6fba709e52b53ae31218524977546242d489"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v0.14.4/everyapi_linux_amd64.tar.gz"
      sha256 "1699b97f06abf9435621a783719495f4ab9ff02b706683a2cc6819d9335635bc"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v0.14.4/everyapi_linux_arm64.tar.gz"
      sha256 "71b59bc694d4c6a3856fe01120889d8a379ec0933cd9d358aaaaa91045eb579d"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  test do
    assert_match "everyapi", shell_output("#{bin}/everyapi version")
    output = pipe_output("#{bin}/everyapi mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
