# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relaya < Formula
  desc "Relaya CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://relaya.pro"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.8/relaya_darwin_amd64.tar.gz"
      sha256 "cd641542d0dda1d873046a527c47488670d7f7182110fb9a768db4b2aef6df89"

      define_method(:install) do
        bin.install "relaya"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.8/relaya_darwin_arm64.tar.gz"
      sha256 "71020abe6c250786ff854e694fe49937e5ad69e738bf3009fc540dffae361905"

      define_method(:install) do
        bin.install "relaya"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.8/relaya_linux_amd64.tar.gz"
      sha256 "8ea5b2cf39b19874a6dafd6582108f86308686bb9b71f01a9e622dd2af2a63f2"
      define_method(:install) do
        bin.install "relaya"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.8/relaya_linux_arm64.tar.gz"
      sha256 "a209a4edeccb15820adede264d10ae7c2e23a7e3d2a6142d48deac89074d43c4"
      define_method(:install) do
        bin.install "relaya"
      end
    end
  end

  test do
    assert_match "relaya", shell_output("#{bin}/relaya version")
    output = pipe_output("#{bin}/relaya mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
