# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Relaya < Formula
  desc "Relaya CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://relaya.pro"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.0/relaya_darwin_amd64.tar.gz"
      sha256 "e009bd1f70eb9eb302ba4947caac6f27b0400cf194b77ef7f3c2b2a33b6d4887"

      define_method(:install) do
        bin.install "relaya"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.0/relaya_darwin_arm64.tar.gz"
      sha256 "be839c7062a983449462e659884bc7dbd8c9836f853dd9004001d59b89196d1d"

      define_method(:install) do
        bin.install "relaya"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.0/relaya_linux_amd64.tar.gz"
      sha256 "3b2afec2685149baab9f5a9968504cfb2112eb88d38a691143df7e0a93c8e08b"
      define_method(:install) do
        bin.install "relaya"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/relaya-ai/relaya-ai/releases/download/v0.1.0/relaya_linux_arm64.tar.gz"
      sha256 "f744230fa41886b9afb752da5aacb3c75da31f5edbac9143fbf89a3439a26a07"
      define_method(:install) do
        bin.install "relaya"
      end
    end
  end

  test do
    assert_match "relaya", shell_output("#{bin}/relaya version")
    output = pipe_output("#{bin}/relaya mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
